data:
  dataloader_type: txt
  use_multilingual_model: true
  use_prior_interpolator: true
  training_files:
    LJS:
      basedir: multilingual-dataset/LJSpeech-1.0/
      sampling_rate: 22khz
      filelist_basdir: multilingual-dataset/LJSpeech-1.0/
      filelist: ljs_audiopath_text_sid_emotion_duration_train_filelist.txt
      language: en_US 
  validation_files:
    LJS:
      basedir: multilingual-dataset/LJSpeech-1.0/
      sampling_rate: 22khz
      filelist_basdir: multilingual-dataset/LJSpeech-1.0/
      filelist: ljs_audiopath_text_sid_emotion_duration_val_filelist.txt
      language: en_US
  filter_length: 1024
  hop_length: 256
  win_length: 1024
  sampling_rate: 22050
  n_mel_channels: 80
  mel_fmin: 0.0
  mel_fmax: 8000.0
  f0_min: 80.0
  f0_max: 640.0
  max_wav_value: 32768.0
  return_audio: false
  use_f0: true
  use_energy_avg: true
  use_log_f0: true
  use_scaled_energy: true
  symbol_set: radmmm_phonemizer_marker_segregated
  cleaner_names:
  - radtts_cleaners
  heteronyms_path: tts_text_processing/heteronyms
  phoneme_dict_path: tts_text_processing/cmudict-0.7b
  p_phoneme: 1.0
  handle_phoneme: word
  handle_phoneme_ambiguous: ignore
  phonemizer_cfg: null
  speaker_ids: null
  include_speakers: null
  n_frames: -1
  use_attn_prior_masking: true
  prepend_space_to_text: true
  append_space_to_text: true
  add_bos_eos_to_text: false
  betabinom_cache_path: betabinom_cache
  betabinom_scaling_factor: 0.05
  lmdb_cache_path: null
  dur_min: 0.1
  dur_max: 10.2
  combine_speaker_and_emotion: false
  distance_tx_unvoiced: false
  mel_noise_scale: 0.0
  speaker_map: null
  batch_size: 8
  num_workers: 4
  inference_transcript: scripts/sample_inference_transcript.txt
  use_wave_augmentations: false
  wave_aug_config: 
    aug_types: ["none","scale_formant","scale_formant"]
    aug_scales: [1.0,0.9,1.10]
    aug_probabilities: [0.6,0.2,0.2]
    aug_languages_applicable: ["te_TE","hi_HI","mar_MAR","en_US","fr_FR","de_DE","pt_BR","es_ES","es_MX","en_UK","es_CO"]
    num_aug_in_batch: 1
    randomize_transform: false
    n_augmentations: 2